CREATE TABLE [dbo].[Blogs]
(
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [UpdatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    [Name] NVARCHAR(200) NOT NULL,
    [BlogId] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_Blogs] PRIMARY KEY
    );

