CREATE SCHEMA [Users];
GO

CREATE TABLE [Users].[Accounts]
(
    [AccountId] INT IDENTITY(1,1) NOT NULL CONSTRAINT [PK_Accounts] PRIMARY KEY,
    [UserName] NVARCHAR(100) NOT NULL,
    [Email] NVARCHAR(256) NOT NULL,
    [CreatedAt] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

