using JD.MSBuild.Fluent;
using JD.MSBuild.Fluent.Fluent;
using JD.MSBuild.Fluent.IR;

namespace JDEfcptBuild;

/// <summary>
/// MSBuild package definition scaffolded from JD.Efcpt.Build.xml
/// </summary>
public static class BuildPropsFactory
{
    public static MsBuildProject Create()
    {
        var project = new MsBuildProject { Label = "Generated by JD.MSBuild.Fluent" };
        var p = PropsBuilder.For(project);

        // Mark this as a direct package reference.
        // This marker is used by buildTransitive to only enable generation
        // for direct consumers, not transitive ones.
        p.Comment("Mark this as a direct package reference.\n    This marker is used by buildTransitive to only enable generation\n    for direct consumers, not transitive ones.");
        p.Property("_EfcptIsDirectReference", "true");
        // Import shared props from buildTransitive.
        // This eliminates duplication between build/ and buildTransitive/ folders.
        // The buildTransitive/ version is the canonical source.
        p.Comment("Import shared props from buildTransitive.\n    This eliminates duplication between build/ and buildTransitive/ folders.\n    The buildTransitive/ version is the canonical source.");
        p.Import("..\\buildTransitive\\JD.Efcpt.Build.props");

        return project;
    }

    // Strongly-typed names (optional - uncomment to use)

    // Property names:
    // public readonly struct EfcptIsDirectReference : IMsBuildPropertyName
    // {
    //     public string Name => "_EfcptIsDirectReference";
    // }
}
