using JD.MSBuild.Fluent;
using JD.MSBuild.Fluent.Fluent;
using JD.MSBuild.Fluent.IR;

namespace JDEfcptBuild;

/// <summary>
/// MSBuild package definition scaffolded from JD.Efcpt.Build.xml
/// </summary>
public static class BuildTransitivePropsFactory
{
    public static MsBuildProject Create()
    {
        var project = new MsBuildProject { Label = "Generated by JD.MSBuild.Fluent" };
        var p = PropsBuilder.For(project);

        p.PropertyGroup(null, group =>
        {
            // Enablement: Enabled by default for all consumers.
            //
            // NOTE: This props file is imported from NuGet's build/ folder and therefore only applies to direct consumers of this package.
            // However, the actual code generation will only run if valid inputs are found:
            // - A SQL project reference (*.sqlproj or MSBuild.Sdk.SqlProj), OR
            // - An explicit DACPAC path (EfcptDacpac), OR
            // - Explicit connection string configuration (EfcptConnectionString, EfcptAppSettings, EfcptAppConfig)
            //
            // Transitive consumers without SQL project references will NOT auto-discover connection
            // strings from their appsettings.json - this prevents WebApi projects from accidentally
            // triggering model generation.
            //
            // To explicitly disable, set:
            // <EfcptEnabled>false</EfcptEnabled>
            group.Comment("Enablement: Enabled by default for all consumers.\n\n      NOTE: This props file is imported from NuGet's build/ folder and therefore only applies to direct consumers of this package.\n      However, the actual code generation will only run if valid inputs are found:\n      - A SQL project reference (*.sqlproj or MSBuild.Sdk.SqlProj), OR\n      - An explicit DACPAC path (EfcptDacpac), OR\n      - Explicit connection string configuration (EfcptConnectionString, EfcptAppSettings, EfcptAppConfig)\n\n      Transitive consumers without SQL project references will NOT auto-discover connection\n      strings from their appsettings.json - this prevents WebApi projects from accidentally\n      triggering model generation.\n\n      To explicitly disable, set:\n        <EfcptEnabled>false</EfcptEnabled>");
            group.Property("EfcptEnabled", "true", "'$(EfcptEnabled)'==''");
            // Output
            group.Comment("Output");
            group.Property("EfcptOutput", "$(BaseIntermediateOutputPath)efcpt\\", "'$(EfcptOutput)'==''");
            group.Property("EfcptGeneratedDir", "$(EfcptOutput)Generated\\", "'$(EfcptGeneratedDir)'==''");
            // Input overrides
            group.Comment("Input overrides");
            group.Property("EfcptSqlProj", "", "'$(EfcptSqlProj)'==''");
            group.Property("EfcptDacpac", "", "'$(EfcptDacpac)'==''");
            group.Property("EfcptConfig", "efcpt-config.json", "'$(EfcptConfig)'==''");
            group.Property("EfcptRenaming", "efcpt.renaming.json", "'$(EfcptRenaming)'==''");
            group.Property("EfcptTemplateDir", "Template", "'$(EfcptTemplateDir)'==''");
            // Connection String Configuration
            group.Comment("Connection String Configuration");
            group.Property("EfcptConnectionString", "", "'$(EfcptConnectionString)'==''");
            group.Property("EfcptAppSettings", "", "'$(EfcptAppSettings)'==''");
            group.Property("EfcptAppConfig", "", "'$(EfcptAppConfig)'==''");
            group.Property("EfcptConnectionStringName", "DefaultConnection", "'$(EfcptConnectionStringName)'==''");
            // Database provider: mssql (default), postgres, mysql, sqlite, oracle, firebird, snowflake
            group.Comment("Database provider: mssql (default), postgres, mysql, sqlite, oracle, firebird, snowflake");
            group.Property("EfcptProvider", "mssql", "'$(EfcptProvider)'==''");
            // Solution probing
            group.Comment("Solution probing");
            group.Property("EfcptSolutionDir", "$(SolutionDir)", "'$(EfcptSolutionDir)'==''");
            group.Property("EfcptSolutionPath", "$(SolutionPath)", "'$(EfcptSolutionPath)'==''");
            group.Property("EfcptProbeSolutionDir", "true", "'$(EfcptProbeSolutionDir)'==''");
            // Tooling
            group.Comment("Tooling");
            group.Property("EfcptToolMode", "auto", "'$(EfcptToolMode)'==''");
            group.Property("EfcptToolPackageId", "ErikEJ.EFCorePowerTools.Cli", "'$(EfcptToolPackageId)'==''");
            group.Property("EfcptToolVersion", "10.*", "'$(EfcptToolVersion)'==''");
            group.Property("EfcptToolRestore", "true", "'$(EfcptToolRestore)'==''");
            group.Property("EfcptToolCommand", "efcpt", "'$(EfcptToolCommand)'==''");
            group.Property("EfcptToolPath", "", "'$(EfcptToolPath)'==''");
            group.Property("EfcptDotNetExe", "dotnet", "'$(EfcptDotNetExe)'==''");
            // Fingerprinting
            group.Comment("Fingerprinting");
            group.Property("EfcptFingerprintFile", "$(EfcptOutput)fingerprint.txt", "'$(EfcptFingerprintFile)'==''");
            group.Property("EfcptStampFile", "$(EfcptOutput).efcpt.stamp", "'$(EfcptStampFile)'==''");
            group.Property("EfcptDetectGeneratedFileChanges", "false", "'$(EfcptDetectGeneratedFileChanges)'==''");
            // Diagnostics
            group.Comment("Diagnostics");
            group.Property("EfcptLogVerbosity", "minimal", "'$(EfcptLogVerbosity)'==''");
            group.Property("EfcptDumpResolvedInputs", "false", "'$(EfcptDumpResolvedInputs)'==''");
            // Warning Level Configuration: Controls the severity of build-time diagnostic messages.
            //
            // EfcptAutoDetectWarningLevel: Severity for SQL project or connection string auto-detection.
            // Valid values: "None", "Info", "Warn", "Error". Defaults to "Info".
            //
            // EfcptSdkVersionWarningLevel: Severity for SDK version update notifications.
            // Valid values: "None", "Info", "Warn", "Error". Defaults to "Warn".
            group.Comment("Warning Level Configuration: Controls the severity of build-time diagnostic messages.\n      \n      EfcptAutoDetectWarningLevel: Severity for SQL project or connection string auto-detection.\n      Valid values: \"None\", \"Info\", \"Warn\", \"Error\". Defaults to \"Info\".\n      \n      EfcptSdkVersionWarningLevel: Severity for SDK version update notifications.\n      Valid values: \"None\", \"Info\", \"Warn\", \"Error\". Defaults to \"Warn\".");
            group.Property("EfcptAutoDetectWarningLevel", "Info", "'$(EfcptAutoDetectWarningLevel)'==''");
            group.Property("EfcptSdkVersionWarningLevel", "Warn", "'$(EfcptSdkVersionWarningLevel)'==''");
            // SDK Version Check: Opt-in feature to check for newer SDK versions on NuGet.
            // Enable with EfcptCheckForUpdates=true. Results are cached to avoid network
            // calls on every build. This helps SDK users stay up-to-date since NuGet's
            // SDK resolver doesn't support floating versions or automatic update notifications.
            group.Comment("SDK Version Check: Opt-in feature to check for newer SDK versions on NuGet.\n      Enable with EfcptCheckForUpdates=true. Results are cached to avoid network\n      calls on every build. This helps SDK users stay up-to-date since NuGet's\n      SDK resolver doesn't support floating versions or automatic update notifications.");
            group.Property("EfcptCheckForUpdates", "false", "'$(EfcptCheckForUpdates)'==''");
            group.Property("EfcptUpdateCheckCacheHours", "24", "'$(EfcptUpdateCheckCacheHours)'==''");
            group.Property("EfcptForceUpdateCheck", "false", "'$(EfcptForceUpdateCheck)'==''");
            // Split Outputs: separate a primary Models project from a secondary Data project.
            // Enable EfcptSplitOutputs in the Models project (with EfcptEnabled=true) and
            // set EfcptDataProject to the target Data project that should receive DbContext
            // and configuration classes.
            //
            // The Models project runs efcpt and generates all files. It keeps the entity
            // model classes (for example, in a Models/ subdirectory), and copies DbContext
            // and configuration classes to the configured Data project.
            group.Comment("Split Outputs: separate a primary Models project from a secondary Data project.\n      Enable EfcptSplitOutputs in the Models project (with EfcptEnabled=true) and\n      set EfcptDataProject to the target Data project that should receive DbContext\n      and configuration classes.\n\n      The Models project runs efcpt and generates all files. It keeps the entity\n      model classes (for example, in a Models/ subdirectory), and copies DbContext\n      and configuration classes to the configured Data project.");
            group.Property("EfcptSplitOutputs", "false", "'$(EfcptSplitOutputs)'==''");
            group.Property("EfcptDataProject", "", "'$(EfcptDataProject)'==''");
            group.Property("EfcptDataProjectOutputSubdir", "obj\\efcpt\\Generated\\", "'$(EfcptDataProjectOutputSubdir)'==''");
            // External Data: for Data project to include DbContext/configs copied from Models project
            group.Comment("External Data: for Data project to include DbContext/configs copied from Models project");
            group.Property("EfcptExternalDataDir", "", "'$(EfcptExternalDataDir)'==''");
            // Config Overrides: Apply MSBuild properties to override efcpt-config.json values.
            // When EfcptApplyMsBuildOverrides is true (default), properties set below will override
            // the corresponding values in the config file. This allows configuration via MSBuild
            // without editing JSON files directly.
            //
            // When using the library default config, overrides are ALWAYS applied.
            // When using a user-provided config, overrides are only applied if EfcptApplyMsBuildOverrides=true.
            group.Comment("Config Overrides: Apply MSBuild properties to override efcpt-config.json values.\n      When EfcptApplyMsBuildOverrides is true (default), properties set below will override\n      the corresponding values in the config file. This allows configuration via MSBuild\n      without editing JSON files directly.\n\n      When using the library default config, overrides are ALWAYS applied.\n      When using a user-provided config, overrides are only applied if EfcptApplyMsBuildOverrides=true.");
            group.Property("EfcptApplyMsBuildOverrides", "true", "'$(EfcptApplyMsBuildOverrides)'==''");
            // Names section overrides
            group.Comment("Names section overrides");
            // Use RootNamespace if defined, otherwise fall back to project name for zero-config scenarios
            group.Comment("Use RootNamespace if defined, otherwise fall back to project name for zero-config scenarios");
            group.Property("EfcptConfigRootNamespace", "$(RootNamespace)", "'$(EfcptConfigRootNamespace)'=='' and '$(RootNamespace)'!=''");
            group.Property("EfcptConfigRootNamespace", "$(MSBuildProjectName)", "'$(EfcptConfigRootNamespace)'==''");
            group.Property("EfcptConfigDbContextName", "", "'$(EfcptConfigDbContextName)'==''");
            group.Property("EfcptConfigDbContextNamespace", "", "'$(EfcptConfigDbContextNamespace)'==''");
            group.Property("EfcptConfigModelNamespace", "", "'$(EfcptConfigModelNamespace)'==''");
            // File layout section overrides
            group.Comment("File layout section overrides");
            group.Property("EfcptConfigOutputPath", "", "'$(EfcptConfigOutputPath)'==''");
            group.Property("EfcptConfigDbContextOutputPath", "", "'$(EfcptConfigDbContextOutputPath)'==''");
            group.Property("EfcptConfigSplitDbContext", "", "'$(EfcptConfigSplitDbContext)'==''");
            group.Property("EfcptConfigUseSchemaFolders", "", "'$(EfcptConfigUseSchemaFolders)'==''");
            group.Property("EfcptConfigUseSchemaNamespaces", "", "'$(EfcptConfigUseSchemaNamespaces)'==''");
            // Code generation section overrides
            group.Comment("Code generation section overrides");
            group.Property("EfcptConfigEnableOnConfiguring", "", "'$(EfcptConfigEnableOnConfiguring)'==''");
            group.Property("EfcptConfigGenerationType", "", "'$(EfcptConfigGenerationType)'==''");
            group.Property("EfcptConfigUseDatabaseNames", "", "'$(EfcptConfigUseDatabaseNames)'==''");
            group.Property("EfcptConfigUseDataAnnotations", "", "'$(EfcptConfigUseDataAnnotations)'==''");
            // NOTE: UseNullableReferenceTypes is set in the targets file (not here) for proper property evaluation order
            group.Comment("NOTE: UseNullableReferenceTypes is set in the targets file (not here) for proper property evaluation order");
            group.Property("EfcptConfigUseInflector", "", "'$(EfcptConfigUseInflector)'==''");
            group.Property("EfcptConfigUseLegacyInflector", "", "'$(EfcptConfigUseLegacyInflector)'==''");
            group.Property("EfcptConfigUseManyToManyEntity", "", "'$(EfcptConfigUseManyToManyEntity)'==''");
            group.Property("EfcptConfigUseT4", "", "'$(EfcptConfigUseT4)'==''");
            group.Property("EfcptConfigUseT4Split", "", "'$(EfcptConfigUseT4Split)'==''");
            group.Property("EfcptConfigRemoveDefaultSqlFromBool", "", "'$(EfcptConfigRemoveDefaultSqlFromBool)'==''");
            group.Property("EfcptConfigSoftDeleteObsoleteFiles", "", "'$(EfcptConfigSoftDeleteObsoleteFiles)'==''");
            group.Property("EfcptConfigDiscoverMultipleResultSets", "", "'$(EfcptConfigDiscoverMultipleResultSets)'==''");
            group.Property("EfcptConfigUseAlternateResultSetDiscovery", "", "'$(EfcptConfigUseAlternateResultSetDiscovery)'==''");
            group.Property("EfcptConfigT4TemplatePath", "", "'$(EfcptConfigT4TemplatePath)'==''");
            group.Property("EfcptConfigUseNoNavigations", "", "'$(EfcptConfigUseNoNavigations)'==''");
            group.Property("EfcptConfigMergeDacpacs", "", "'$(EfcptConfigMergeDacpacs)'==''");
            group.Property("EfcptConfigRefreshObjectLists", "", "'$(EfcptConfigRefreshObjectLists)'==''");
            group.Property("EfcptConfigGenerateMermaidDiagram", "", "'$(EfcptConfigGenerateMermaidDiagram)'==''");
            group.Property("EfcptConfigUseDecimalAnnotationForSprocs", "", "'$(EfcptConfigUseDecimalAnnotationForSprocs)'==''");
            group.Property("EfcptConfigUsePrefixNavigationNaming", "", "'$(EfcptConfigUsePrefixNavigationNaming)'==''");
            group.Property("EfcptConfigUseDatabaseNamesForRoutines", "", "'$(EfcptConfigUseDatabaseNamesForRoutines)'==''");
            group.Property("EfcptConfigUseInternalAccessForRoutines", "", "'$(EfcptConfigUseInternalAccessForRoutines)'==''");
            // Type mappings section overrides
            group.Comment("Type mappings section overrides");
            group.Property("EfcptConfigUseDateOnlyTimeOnly", "", "'$(EfcptConfigUseDateOnlyTimeOnly)'==''");
            group.Property("EfcptConfigUseHierarchyId", "", "'$(EfcptConfigUseHierarchyId)'==''");
            group.Property("EfcptConfigUseSpatial", "", "'$(EfcptConfigUseSpatial)'==''");
            group.Property("EfcptConfigUseNodaTime", "", "'$(EfcptConfigUseNodaTime)'==''");
            // Replacements section overrides
            group.Comment("Replacements section overrides");
            group.Property("EfcptConfigPreserveCasingWithRegex", "", "'$(EfcptConfigPreserveCasingWithRegex)'==''");
            // SQL Project Detection: Moved to targets file to ensure properties are set.
            // See _EfcptDetectSqlProject target in JD.Efcpt.Build.targets.
            group.Comment("SQL Project Detection: Moved to targets file to ensure properties are set.\n      See _EfcptDetectSqlProject target in JD.Efcpt.Build.targets.");
            // Build Profiling: Optional, configurable profiling framework to capture timing,
            // task execution, and diagnostics for performance analysis and benchmarking.
            //
            // EfcptEnableProfiling: Enable/disable profiling (default: false)
            // EfcptProfilingOutput: Path where the profiling JSON file will be written
            // (default: $(EfcptOutput)build-profile.json)
            // EfcptProfilingVerbosity: Controls the level of detail captured in the profile
            // (values: "minimal", "detailed"; default: "minimal")
            group.Comment("Build Profiling: Optional, configurable profiling framework to capture timing,\n      task execution, and diagnostics for performance analysis and benchmarking.\n      \n      EfcptEnableProfiling: Enable/disable profiling (default: false)\n      EfcptProfilingOutput: Path where the profiling JSON file will be written\n        (default: $(EfcptOutput)build-profile.json)\n      EfcptProfilingVerbosity: Controls the level of detail captured in the profile\n        (values: \"minimal\", \"detailed\"; default: \"minimal\")");
            group.Property("EfcptEnableProfiling", "false", "'$(EfcptEnableProfiling)'==''");
            group.Property("EfcptProfilingOutput", "$(EfcptOutput)build-profile.json", "'$(EfcptProfilingOutput)'==''");
            group.Property("EfcptProfilingVerbosity", "minimal", "'$(EfcptProfilingVerbosity)'==''");
        });
        p.PropertyGroup(null, group =>
        {
            // SQL Project Generation Configuration
            group.Comment("SQL Project Generation Configuration");
            group.Property("EfcptSqlProjType", "microsoft-build-sql", "'$(EfcptSqlProjType)'==''");
            group.Property("EfcptSqlProjLanguage", "csharp", "'$(EfcptSqlProjLanguage)'==''");
            group.Property("EfcptSqlProjOutputDir", "$(MSBuildProjectDirectory)\\", "'$(EfcptSqlProjOutputDir)'==''");
            group.Property("EfcptSqlScriptsDir", "$(MSBuildProjectDirectory)\\", "'$(EfcptSqlScriptsDir)'==''");
            group.Property("EfcptSqlServerVersion", "Sql160", "'$(EfcptSqlServerVersion)'==''");
            group.Property("EfcptSqlPackageToolVersion", "", "'$(EfcptSqlPackageToolVersion)'==''");
            group.Property("EfcptSqlPackageToolRestore", "true", "'$(EfcptSqlPackageToolRestore)'==''");
            group.Property("EfcptSqlPackageToolPath", "", "'$(EfcptSqlPackageToolPath)'==''");
        });

        return project;
    }

    // Strongly-typed names (optional - uncomment to use)

    // Property names:
    // public readonly struct EfcptAppConfig : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptAppConfig";
    // }
    // public readonly struct EfcptApplyMsBuildOverrides : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptApplyMsBuildOverrides";
    // }
    // public readonly struct EfcptAppSettings : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptAppSettings";
    // }
    // public readonly struct EfcptAutoDetectWarningLevel : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptAutoDetectWarningLevel";
    // }
    // public readonly struct EfcptCheckForUpdates : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptCheckForUpdates";
    // }
    // public readonly struct EfcptConfig : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfig";
    // }
    // public readonly struct EfcptConfigDbContextName : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigDbContextName";
    // }
    // public readonly struct EfcptConfigDbContextNamespace : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigDbContextNamespace";
    // }
    // public readonly struct EfcptConfigDbContextOutputPath : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigDbContextOutputPath";
    // }
    // public readonly struct EfcptConfigDiscoverMultipleResultSets : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigDiscoverMultipleResultSets";
    // }
    // public readonly struct EfcptConfigEnableOnConfiguring : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigEnableOnConfiguring";
    // }
    // public readonly struct EfcptConfigGenerateMermaidDiagram : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigGenerateMermaidDiagram";
    // }
    // public readonly struct EfcptConfigGenerationType : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigGenerationType";
    // }
    // public readonly struct EfcptConfigMergeDacpacs : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigMergeDacpacs";
    // }
    // public readonly struct EfcptConfigModelNamespace : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigModelNamespace";
    // }
    // public readonly struct EfcptConfigOutputPath : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigOutputPath";
    // }
    // public readonly struct EfcptConfigPreserveCasingWithRegex : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigPreserveCasingWithRegex";
    // }
    // public readonly struct EfcptConfigRefreshObjectLists : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigRefreshObjectLists";
    // }
    // public readonly struct EfcptConfigRemoveDefaultSqlFromBool : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigRemoveDefaultSqlFromBool";
    // }
    // public readonly struct EfcptConfigRootNamespace : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigRootNamespace";
    // }
    // public readonly struct EfcptConfigSoftDeleteObsoleteFiles : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigSoftDeleteObsoleteFiles";
    // }
    // public readonly struct EfcptConfigSplitDbContext : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigSplitDbContext";
    // }
    // public readonly struct EfcptConfigT4TemplatePath : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigT4TemplatePath";
    // }
    // public readonly struct EfcptConfigUseAlternateResultSetDiscovery : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseAlternateResultSetDiscovery";
    // }
    // public readonly struct EfcptConfigUseDataAnnotations : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseDataAnnotations";
    // }
    // public readonly struct EfcptConfigUseDatabaseNames : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseDatabaseNames";
    // }
    // public readonly struct EfcptConfigUseDatabaseNamesForRoutines : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseDatabaseNamesForRoutines";
    // }
    // public readonly struct EfcptConfigUseDateOnlyTimeOnly : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseDateOnlyTimeOnly";
    // }
    // public readonly struct EfcptConfigUseDecimalAnnotationForSprocs : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseDecimalAnnotationForSprocs";
    // }
    // public readonly struct EfcptConfigUseHierarchyId : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseHierarchyId";
    // }
    // public readonly struct EfcptConfigUseInflector : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseInflector";
    // }
    // public readonly struct EfcptConfigUseInternalAccessForRoutines : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseInternalAccessForRoutines";
    // }
    // public readonly struct EfcptConfigUseLegacyInflector : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseLegacyInflector";
    // }
    // public readonly struct EfcptConfigUseManyToManyEntity : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseManyToManyEntity";
    // }
    // public readonly struct EfcptConfigUseNodaTime : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseNodaTime";
    // }
    // public readonly struct EfcptConfigUseNoNavigations : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseNoNavigations";
    // }
    // public readonly struct EfcptConfigUsePrefixNavigationNaming : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUsePrefixNavigationNaming";
    // }
    // public readonly struct EfcptConfigUseSchemaFolders : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseSchemaFolders";
    // }
    // public readonly struct EfcptConfigUseSchemaNamespaces : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseSchemaNamespaces";
    // }
    // public readonly struct EfcptConfigUseSpatial : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseSpatial";
    // }
    // public readonly struct EfcptConfigUseT4 : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseT4";
    // }
    // public readonly struct EfcptConfigUseT4Split : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConfigUseT4Split";
    // }
    // public readonly struct EfcptConnectionString : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConnectionString";
    // }
    // public readonly struct EfcptConnectionStringName : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptConnectionStringName";
    // }
    // public readonly struct EfcptDacpac : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptDacpac";
    // }
    // public readonly struct EfcptDataProject : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptDataProject";
    // }
    // public readonly struct EfcptDataProjectOutputSubdir : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptDataProjectOutputSubdir";
    // }
    // public readonly struct EfcptDetectGeneratedFileChanges : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptDetectGeneratedFileChanges";
    // }
    // public readonly struct EfcptDotNetExe : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptDotNetExe";
    // }
    // public readonly struct EfcptDumpResolvedInputs : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptDumpResolvedInputs";
    // }
    // public readonly struct EfcptEnabled : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptEnabled";
    // }
    // public readonly struct EfcptEnableProfiling : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptEnableProfiling";
    // }
    // public readonly struct EfcptExternalDataDir : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptExternalDataDir";
    // }
    // public readonly struct EfcptFingerprintFile : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptFingerprintFile";
    // }
    // public readonly struct EfcptForceUpdateCheck : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptForceUpdateCheck";
    // }
    // public readonly struct EfcptGeneratedDir : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptGeneratedDir";
    // }
    // public readonly struct EfcptLogVerbosity : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptLogVerbosity";
    // }
    // public readonly struct EfcptOutput : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptOutput";
    // }
    // public readonly struct EfcptProbeSolutionDir : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptProbeSolutionDir";
    // }
    // public readonly struct EfcptProfilingOutput : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptProfilingOutput";
    // }
    // public readonly struct EfcptProfilingVerbosity : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptProfilingVerbosity";
    // }
    // public readonly struct EfcptProvider : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptProvider";
    // }
    // public readonly struct EfcptRenaming : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptRenaming";
    // }
    // public readonly struct EfcptSdkVersionWarningLevel : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSdkVersionWarningLevel";
    // }
    // public readonly struct EfcptSolutionDir : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSolutionDir";
    // }
    // public readonly struct EfcptSolutionPath : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSolutionPath";
    // }
    // public readonly struct EfcptSplitOutputs : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSplitOutputs";
    // }
    // public readonly struct EfcptSqlPackageToolPath : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlPackageToolPath";
    // }
    // public readonly struct EfcptSqlPackageToolRestore : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlPackageToolRestore";
    // }
    // public readonly struct EfcptSqlPackageToolVersion : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlPackageToolVersion";
    // }
    // public readonly struct EfcptSqlProj : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlProj";
    // }
    // public readonly struct EfcptSqlProjLanguage : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlProjLanguage";
    // }
    // public readonly struct EfcptSqlProjOutputDir : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlProjOutputDir";
    // }
    // public readonly struct EfcptSqlProjType : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlProjType";
    // }
    // public readonly struct EfcptSqlScriptsDir : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlScriptsDir";
    // }
    // public readonly struct EfcptSqlServerVersion : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptSqlServerVersion";
    // }
    // public readonly struct EfcptStampFile : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptStampFile";
    // }
    // public readonly struct EfcptTemplateDir : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptTemplateDir";
    // }
    // public readonly struct EfcptToolCommand : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptToolCommand";
    // }
    // public readonly struct EfcptToolMode : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptToolMode";
    // }
    // public readonly struct EfcptToolPackageId : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptToolPackageId";
    // }
    // public readonly struct EfcptToolPath : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptToolPath";
    // }
    // public readonly struct EfcptToolRestore : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptToolRestore";
    // }
    // public readonly struct EfcptToolVersion : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptToolVersion";
    // }
    // public readonly struct EfcptUpdateCheckCacheHours : IMsBuildPropertyName
    // {
    //     public string Name => "EfcptUpdateCheckCacheHours";
    // }
}
